# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_controle_estufa5.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_controle_estufa(object):
    def setupUi(self, controle_estufa):
        controle_estufa.setObjectName("controle_estufa")
        controle_estufa.resize(412, 325)
        self.centralwidget = QtWidgets.QWidget(controle_estufa)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 270, 391, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ventilador = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ventilador.setObjectName("ventilador")
        self.horizontalLayout.addWidget(self.ventilador)
        self.regador = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.regador.setObjectName("regador")
        self.horizontalLayout.addWidget(self.regador)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 150, 391, 111))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lcd_temperatura = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_2)
        self.lcd_temperatura.setMidLineWidth(0)
        self.lcd_temperatura.setSmallDecimalPoint(False)
        self.lcd_temperatura.setDigitCount(3)
        self.lcd_temperatura.setObjectName("lcd_temperatura")
        self.horizontalLayout_2.addWidget(self.lcd_temperatura)
        self.lcd_umidade = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_2)
        self.lcd_umidade.setDigitCount(3)
        self.lcd_umidade.setProperty("intValue", 0)
        self.lcd_umidade.setObjectName("lcd_umidade")
        self.horizontalLayout_2.addWidget(self.lcd_umidade)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 90, 391, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Estabelecer_conexao = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Estabelecer_conexao.setObjectName("Estabelecer_conexao")
        self.verticalLayout.addWidget(self.Estabelecer_conexao)
        self.barra_de_conexao = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.barra_de_conexao.setProperty("value", 0)
        self.barra_de_conexao.setObjectName("barra_de_conexao")
        self.verticalLayout.addWidget(self.barra_de_conexao)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(240, 0, 160, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.iniciar_medicoes = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.iniciar_medicoes.setEnabled(True)
        self.iniciar_medicoes.setObjectName("iniciar_medicoes")
        self.verticalLayout_2.addWidget(self.iniciar_medicoes)
        self.parar_medicoes = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.parar_medicoes.setObjectName("parar_medicoes")
        self.verticalLayout_2.addWidget(self.parar_medicoes)
        #controle_estufa.setCentralWidget(self.centralwidget)

        self.retranslateUi(controle_estufa)
        QtCore.QMetaObject.connectSlotsByName(controle_estufa)

    def retranslateUi(self, controle_estufa):
        _translate = QtCore.QCoreApplication.translate
        controle_estufa.setWindowTitle(_translate("controle_estufa", "Controle de Estufa"))
        self.ventilador.setText(_translate("controle_estufa", "Ventilar"))
        self.regador.setText(_translate("controle_estufa", "Regar"))
        self.label_2.setText(_translate("controle_estufa", "Temperatura [°C]"))
        self.label.setText(_translate("controle_estufa", "Umidade do solo [%]"))
        self.Estabelecer_conexao.setText(_translate("controle_estufa", "Estabelecer conexão"))
        self.iniciar_medicoes.setText(_translate("controle_estufa", "Iniciar medições"))
        self.parar_medicoes.setText(_translate("controle_estufa", "Parar Medições"))
